### PR TITLE
Fix Construction From JSON

### LINKED ISSUE #47: JSON-reader unit test hangs
The unit test for the constructor that reads a JSON object is commented out at [line 23] in test/dag_test.f90.  Adding that test causes the tests to hang. @everythingfunctional could you take a look at this?

[line 23]:  https://github.com/sourceryinstitute/dag/blob/af3aea26f1bd0cb3c6d2e84446186a08a429cfce/test/dag_test.f90#L23]

### PR DESCRIPTION
**Pull request by everythingfunctional**
Bypass formatted read and fix the constructor from json

Fix #47

### CODE REVIEW

File: src/dag_s.f90 [hunk 1]
```diff
@@ -106,55 +106,30 @@ end function toposort
...
-              call assert(.false., "dag_s construct_from_json: vertex was not an object", char(vertex_json%to_compact_string()))
-            type is (json_object_t)
-              associate(dag_vertex => vertex_t(vertex_json))
-                call dag%vertices(i)%set_edges(dag_vertex%edges)
-              end associate
-            end select
-          end associate
-        end do
-      end block
+      dag%vertices = vertex_t(vertices%get_elements())
```
Comment (rouson) [inline src/dag_s.f90:127]: @everythingfunctional this is truly elegant and is exactly the sort of thing I had hoped was possible.

**Review by rouson — APPROVED** [review]
LGTM
